// NOTE: Generated By hrp v4.2.0, DO NOT EDIT!
package main

import (
	"github.com/httprunner/funplugin/fungo"
)

func main() {
	fungo.Register("GetCurrentTimestamp", GetCurrentTimestamp)
	fungo.Register("GetAuth", GetAuth)
	fungo.Register("GetPopAuth", GetPopAuth)
	fungo.Register("GetUcwiAuth", GetUcwiAuth)
	fungo.Register("GetUUID", GetUUID)
	fungo.Register("GetUcwiDlpChannelMetadata", GetUcwiDlpChannelMetadata)
	fungo.Register("GetRandomFile", GetRandomFile)
	fungo.Register("GetRandomData", GetRandomData)
	fungo.Register("RandInt", RandInt)
	fungo.Serve()
}
